
baseURL = "https://yrachid.com/"
languageCode = "en-us"
title = "Yasser Rachid"

theme = "coder"

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[permalinks]
    post = "posts/:title/"
    default = ":title/"

[params]
    info = "Writings"
    description = "yrachid.toString()"
    keywords = "blog,developer,personal"

[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"

[[menu.main]]
    name = "Github"
    weight = 2
    url = "https://github.com/yrachid"
