
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Yasser Rachid"

theme = "coder"

[permalinks]
    post = "posts/:title/"
    default = ":title/"

[params] # theme parameters
    info = "Thoughts about software and stuff"
    description = "John Doe's personal website"
    keywords = "blog,developer,personal"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/othman853"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/ylrachid/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
